[config]
repeat_delay = 500
repeat_rate = 60
mouse_delay = 16
deadzone_mode = axial
deadzone = 2000

[controls]
overlay = "clear"

# Postal 2 keyboard and mouse controls.
a = enter
b = space
x = r
y = c
l1 = e
r1 = q
l2 = mouse_right
r2 = mouse_left
l3 = left_shift
r3 = t
start = esc
back = f

# D-pad selects the previous or next weapon in-game.
up = mwheelup
down = mwheeldown
left = [
right = ]

left_analog_up = w
left_analog_down = s
left_analog_left = a
left_analog_right = d
right_analog = mouse_movement

[controls:menu]
overlay = "clear"
start = enter
back = esc
up = up
down = down
left = left
right = right
a = enter
b = esc
