#ifndef POSTAL2_FRAME_H
#define POSTAL2_FRAME_H

#define POSTAL2_FRAME_PATH "/tmp/postal2.frame"
#define POSTAL2_FRAME_MAGIC 0x4e465342u
#define POSTAL2_FRAME_MAX_W 1280
#define POSTAL2_FRAME_MAX_H 768
#define POSTAL2_FRAME_HDR 64
#define POSTAL2_FRAME_FILE_SIZE \
    (POSTAL2_FRAME_HDR + (size_t)POSTAL2_FRAME_MAX_W * (size_t)POSTAL2_FRAME_MAX_H * 4u)

#define POSTAL2_HDR_MAGIC 0
#define POSTAL2_HDR_SEQ 1
#define POSTAL2_HDR_W 2
#define POSTAL2_HDR_H 3
#define POSTAL2_HDR_READY 4
#define POSTAL2_HDR_BUTTONS 5
#define POSTAL2_HDR_AXIS0 6
#define POSTAL2_HDR_PAD_SEQ 12
#define POSTAL2_HDR_CURSOR_X 13
#define POSTAL2_HDR_CURSOR_Y 14
#define POSTAL2_HDR_CURSOR_ON 15

#endif
