Section "Files"
    ModulePath "/tmp/xvfb-postal2/usr/lib/xorg/modules"
EndSection

Section "Module"
    Load "glx"
EndSection

Section "ServerFlags"
    Option "AIGLX" "on"
    Option "AllowIndirectGLX" "on"
EndSection
